AWSTemplateFormatVersion: "2010-09-09"
Description: ALB Create

Resources:
#セキュリティグループ
  TestAlbSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: ALB SG
        GroupName: !Sub ${AWS::StackName}-sg
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
        Tags:
          - Key: Name
            Value: !Sub ${AWS::StackName}-sg
        VpcId: !ImportValue TestVPC
#ALB
  TestALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: !Sub ${AWS::StackName}
      Scheme: internet-facing
      SecurityGroups: 
        - !Ref TestAlbSG
      Subnets: 
        - !ImportValue TestPublicSubNet1a
        - !ImportValue TestPublicSubNet1c
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}
      Type: application
  ListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !ImportValue CfTargetGroup
      LoadBalancerArn: !Ref TestALB
      Port: 80
      Protocol: HTTP
