AWSTemplateFormatVersion: "2010-09-09"
Description: LoadBalancer

Parameters:
  PJPrefix:
    Type: String

Resources:
#securitygroup-http
  TestAlbSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: ALB SG
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
        Tags:
          - Key: Name
            Value: !Sub ${PJPrefix}-AlbSG
        VpcId: !ImportValue 
          Fn::Sub: ${PJPrefix}-Vpc
#ALB
  TestALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups: 
        - !Ref TestAlbSG
      Subnets: 
        - !ImportValue 
            Fn::Sub: ${PJPrefix}-PublicSubNet1a
        - !ImportValue 
            Fn::Sub: ${PJPrefix}-PublicSubNet1c
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-Alb
      Type: application
  ListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !ImportValue 
            Fn::Sub: ${PJPrefix}-TargetGroup
      LoadBalancerArn: !Ref TestALB
      Port: 80
      Protocol: HTTP
