AWSTemplateFormatVersion: "2010-09-09"
Description: TargetGroup

Parameters:
  PJPrefix:
    Type: String

#TargetGroup
Resources:
  CfTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Matcher: 
        HttpCode: 200-399
      Port: 80
      Protocol: HTTP
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-TargetGroup
      TargetType: instance
      VpcId: !ImportValue
        Fn::Sub: ${PJPrefix}-Vpc
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
Outputs:
  TargetGroup:
    Value: !Ref CfTargetGroup
    Export: 
      Name: !Sub ${PJPrefix}-TargetGroup